
name: Node.js CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # 원하는 Node.js 버전을 지정

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests
    - name: Run tests
      run: npm test

    # Build the project (optional, if your project requires a build step)
    - name: Build project
      run: npm run build

    # Optionally upload test results or artifacts
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./test-results  # 테스트 결과 파일 경로 지정

