name: Node.js CI

on:
  push:
    branches: [ "main", "testBranch" ]
  pull_request:
    branches: [ "main", "testBranch" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Clean NPM Cache and Install Dependencies
        run: |
          npm cache clean --force
          npm ci
        working-directory: .

      - name: Print Node and NPM Versions
        run: |
          node -v
          npm -v

      - name: Run Tests
        run: npm test
        working-directory: .
