name: Frontend Unit Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # LTS 버전을 사용합니다. 필요에 따라 수정 가능

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Run Jest tests
      - name: Run Tests with Jest
        run: npm test

      # 5. Report coverage (optional)
      - name: Upload Test Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/*.json
          flags: unittests
          name: frontend-tests
          fail_ci_if_error: true
