name: CI Pipeline - Unit Tests

on:
  push:
    branches: [ Backend_SimpleResult ]
  pull_request:
    branches: [ main ]

jobs:
  # Unit Test for Create Question
  test-create-question:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run test for createQuestion method
        working-directory: CampusShare_demo
        run: |
          chmod +x gradlew
          ./gradlew clean test --tests "*QuestionCreateTest"

  # Unit Test for Get All Questions
  test-get-all-questions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run test for getAllQuestions method
        working-directory: CampusShare_demo
        run: |
          chmod +x gradlew
          ./gradlew clean test --tests "*QuestionGetAllTest"
